[package]
name = "simple-grid"
description = "A simple 2d-grid structure"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["2d", "array", "grid", "map"]
categories = ["data-structures"]
repository = "https://github.com/ijagberg/grid"
homepage = "https://github.com/ijagberg/grid"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
