name: Rust

on:
  push:
    branches: [feature/*]
    paths:
      - "src/*"
      - "examples/*"
      - ".github/**"
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --all-features
      - name: Lint
        run: cargo clippy --verbose --all-features
      - name: Run tests
        run: cargo test --verbose --all-features
